import mongoose from 'mongoose';

const topicSchema = new mongoose.Schema({
  topicId: { type: String, required: true },
  module: { type: String, required: true },
  title: { type: String, required: true },
  description: { type: String },
  lectureHours: { type: Number },
  isCompleted: { type: Boolean, default: false },
  targetDate: { type: Date }, // The date generated by Gemini
});

const syllabusSchema = new mongoose.Schema({
  courseId: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    ref: 'Course',
  },
  topics: [topicSchema], // An array of topics
}, { timestamps: true });

export default mongoose.model('Syllabus', syllabusSchema);
